### PR TITLE
Add chunked transfer-encoding support

### PR DESCRIPTION
**Pull request by tjdavey**
Adds support for conveniently sending requests with node-form-data using chunked transfer encoding.

This can be used in cases where the server supports chunked encoding and the content length of readable streams cannot be determined without buffering and will assist some users in working around issues like #90 until a permanent solution is found. 

**Usage**

Two possible invocation methods can be used. 

*Custom Submit Option*

```
form.submit({host: 'localhost', port: 80, path: '/', chunked: true}
```

*Custom Header*
```
customHeaders = {
  'transfer-encoding': 'chunked'
}
form.submit({host: 'localhost', port: 80, path: '/', headers: customHeaders}
```

**Notes**
- Tests include a stream with an indiscernible length (HTTP response with chunked encoding itself). 
- Supports multiple, chained transfer codings as per RFC7230
- `chunked` submit option will NOT overwrite other custom set `transfer-encoding` headers.

### CODE REVIEW

**Comment by tjdavey** [comment]
Closing this PR to fix some issues with support for Node 0.8 that came out of Travis.

**Comment by alexindigo** [comment]
I think we're ready to drop 0.8 support. It's time to include accumulated changes and release 1.0 without 0.8 support.

**Comment by tjdavey** [comment]
The only components failing in 0.8 are the tests. I've attempted to work around it but I feel the resultant code is very hacky. If you want to drop 0.8 support i'll reopen this when you're ready. :dancer:

**Comment by alexindigo** [comment]
Can you file PR against `1.0` branch? Thank you.

**Pull request closed without merging**
